# name属性用来指定这个工作流的名字
name: npm-auto-publish

on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'npm-auto-publish'

    environment: npm

    steps:
      - uses: actions/checkout@master

      - name: Install and Build 
        run: |
          npm install
          npm run build # 这是我的项目的打包命令，你也可以改成你的

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        with:
          default_branch: 'master'
