name: npm-publish

on: push
  
jobs:
  # 这是jobs中的一个任务，名字叫npm-publish(随便怎么取名)
  npm-publish:
    # 任务名称
    name: npm-publish
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest
    # 指定环境
    environment: npm
    steps:
      # github actions 自带插件主要是为了检出当前仓库的代码
      - name: fdsf
      - uses: actions/checkout@v2

      # name为该条命令的名字 随便取名字
      - name: fdsf111
      # 在当前操作系统安装node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x' # 指定node.js版本
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}