# name属性用来指定这个工作流的名字
name: npm-publish

on: push
  
jobs:
  # 这是jobs中的一个任务，名字叫npm-publish(随便怎么取名)
  npm-publish:
    # 任务名称
    name: npm-publish
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest
    # 指定环境
    environment: npm
    steps:
      # 使用Github Actions自带的插件
      # 检出当前仓库的代码
      - uses: actions/checkout@v2
      # 在当前操作系统安装node.js，可指定node.js的版本
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x' # 指定node.js版本
          registry-url: 'https://registry.npmjs.org'

      # 运行shell命令
      # 重新清理并安装项目，相当于npm先清理再安装
      - run: npm ci
      # 编译项目
      - run: npm run build
      # 发布npm包
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}